spring:
  application:
    name: camunda
server:
  port: 8090
camunda:
  bpm:
    admin-user:
      id: admin
    filter:
      create: All
logging:
  level:
    root: INFO
    org.camunda.bpm.engine.persistence: WARN
    org.springframework.test.annotation.ProfileValueUtils: WARN
